using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using BepInEx;
using BepInEx.Bootstrap;
using BepInEx.Configuration;
using BepInEx.Logging;
using HarmonyLib;
using UnityEngine;

namespace UniversalRadar
{
    [BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]// ScienceBird.UniversalRadar, UniversalRadar
    [BepInDependency("voxx.TerraMesh", BepInDependency.DependencyFlags.HardDependency)]
    [BepInDependency("imabatby.lethallevelloader", BepInDependency.DependencyFlags.SoftDependency)]
    [BepInDependency("dopadream.lethalcompany.rebalancedmoons", BepInDependency.DependencyFlags.SoftDependency)]
    [BepInDependency("MapImprovements", BepInDependency.DependencyFlags.SoftDependency)]
    [BepInDependency("TonightWeDine", BepInDependency.DependencyFlags.SoftDependency)]
    [BepInDependency("Zaggy1024.TwoRadarMaps", BepInDependency.DependencyFlags.SoftDependency)]
    public class UniversalRadar : BaseUnityPlugin
    {
        public static UniversalRadar Instance { get; private set; } = null!;
        internal new static ManualLogSource Logger { get; private set; } = null!;
        internal static Harmony? Harmony { get; set; }

        public static AssetBundle URAssets;

        public static ConfigEntry<float> AutoLineWidth, AutoSpacing, AutoOpacity;
        public static ConfigEntry<bool> LogValues;
        public static ConfigEntry<bool> OldRadarFallback, UseDefaultLayer, UseTerrainLayer, UseFoliageLayer;
        public static ConfigEntry<bool> UseTerraMesh, HideRadarObjects, RadarWater, ShowTerrain, ShowFoliage;
        public static ConfigEntry<float> RadarObjectSize, CameraClipExtension;
        public static ConfigEntry<bool> ExperimentationSprites, AssuranceSprites, VowSprites, MarchSprites, RendSprites, DineSprites, OffenseSprites, TitanSprites, ArtificeSprites, AdamanceSprites, EmbrionSprites, GordionSprites, ShipInheritColour;
        public static ConfigEntry<string> ExperimentationSpriteColour, AssuranceSpriteColour, VowSpriteColour, MarchSpriteColour, RendSpriteColour, DineSpriteColour, OffenseSpriteColour, TitanSpriteColour, ArtificeSpriteColour, AdamanceSpriteColour, EmbrionSpriteColour, GordionSpriteColour, ShipColour;

        public static ConfigEntry<bool> ClearOrphans;
        public static ConfigEntry<string> ConfigVersion;

        public static Material contourMaterial;
        public static Material radarFillMat0;
        public static Material radarFillMat1;
        public static Material radarWaterMat;

        public static bool batbyPresent = false;
        public static bool zaggyPresent = false;
        public static bool dopaPresent = false;
        public static bool spookyPresent = false;
        public static bool terraformerPresent = false;

        public static int[] configVersionArray = [-1, -1, -1];
        //public static List<ConfigDefinition> tempConfigs = new List<ConfigDefinition>();

        private static float storedTime = 0f;

        private void Awake()
        {
            Logger = base.Logger;
            Instance = this;

            UseTerraMesh = base.Config.Bind("!General", "Convert Terrains To Mesh", true, "When a moon has non-mesh terrain, it will be converted in order to generate the contour map. This will mean a long initial load on maps with non-mesh terrain (this includes most of Wesley's moons), but after the first time, it will store the generated mesh for the rest of the session. If this ends up taking way too long or even causing timeouts/crashes, you can disable it here (though any moons with non-mesh terrain will no longer have contour maps).");
            HideRadarObjects = base.Config.Bind("!General", "Master Disable Radar Objects", false, "Overrides all individual configs and will never attempt to create radar images for non-terrain objects.");
            RadarObjectSize = base.Config.Bind("!General", "Radar Object Display Threshold", 90f, new ConfigDescription("How big objects need to be to render as an object on the radar screen (if that config is enabled on the moon). Make this bigger to display less small objects.", new AcceptableValueRange<float>(50f, 1000f)));
            CameraClipExtension = base.Config.Bind("!General", "Increased Radar Vertical Render Distance", 20f, new ConfigDescription("When outside, the region of space captured by the camera needs to be extended for the 3D contours generated by this mod to be captured. Increasing this means more objects/scenery above and below a player will be picked up on the radar screen (set this to 0 for vanilla clipping distance).", new AcceptableValueRange<float>(0f, 150f)));
            RadarWater = base.Config.Bind("!General", "Show Water On Radar", true, "Generates a special mesh for water objects on vanilla and modded moons.");
            ShowFoliage = base.Config.Bind("!General", "Show Foliage Radar Objects", false, "Includes meshes on the foliage layer when generating radar objects.");

            AutoSpacing = base.Config.Bind("Automatic Settings", "Line Spacing", 2.5f, new ConfigDescription("Spacing between lines in automatically generated contour maps.", new AcceptableValueRange<float>(0.5f, 6f)));
            AutoLineWidth = base.Config.Bind("Automatic Settings", "Line Thickness", 6f, new ConfigDescription("Thickness of lines in automatically generated contour maps.", new AcceptableValueRange<float>(0.5f, 10f)));
            AutoOpacity = base.Config.Bind("Automatic Settings", "Maximum Opacity", 0.9f, new ConfigDescription("Maximum opacity of the shading on automatically generated contour maps (how light the tallest parts of the contour map will be).", new AcceptableValueRange<float>(0.1f, 1f)));
            LogValues = base.Config.Bind("Automatic Settings", "Log Automatic Values", false, "Logs all contour map values (notably the minimum and maximum height) upon generating on a moon. Use this if you want to know the normally calculated values before manually customizing them yourself (or for other debugging purposes).");

            OldRadarFallback = base.Config.Bind("Interior Radar Fallback", "Automatic Fallback To Old Radar", true, "If an interior is detected to lack radar sprites, the old pre-v70 radar will be used when a player is inside that interior.");
            UseDefaultLayer = base.Config.Bind("Interior Radar Fallback", "Include Default Layer", false, "Prior to v70, only objects on the Room (and MapRadar) layers would appear on the radar. Enabling this allows objects on the Default layer (objects not assigned to any layer) to appear as well.");

            ShipInheritColour = base.Config.Bind("Vanilla Radar Sprites", "Match Ship Sprite Colour To Radar", true, "Change the colour of the ship's sprite to match the radar object/sprite colour of whatever moon it's landed on.");
            ShipColour = base.Config.Bind("Vanilla Radar Sprites", "Ship Sprite Colour", "63FF5A", "The colour of the ship sprite at all times (will not work if the above option is enabled).");
            ExperimentationSprites = base.Config.Bind("Vanilla Radar Sprites", "Experimentation", true, "Adds new radar sprites for Experimentation, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            AssuranceSprites = base.Config.Bind("Vanilla Radar Sprites", "Assurance", true, "Adds new radar sprites for Assurance, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            VowSprites = base.Config.Bind("Vanilla Radar Sprites", "Vow", true, "Adds new radar sprites for Vow, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            MarchSprites = base.Config.Bind("Vanilla Radar Sprites", "March", true, "Adds new radar sprites for March, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            RendSprites = base.Config.Bind("Vanilla Radar Sprites", "Rend", true, "Adds new radar sprites for Rend, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            DineSprites = base.Config.Bind("Vanilla Radar Sprites", "Dine", true, "Adds new radar sprites for Dine, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            OffenseSprites = base.Config.Bind("Vanilla Radar Sprites", "Offense", true, "Adds new radar sprites for Offense, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            TitanSprites = base.Config.Bind("Vanilla Radar Sprites", "Titan", true, "Adds new radar sprites for Titan, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            ArtificeSprites = base.Config.Bind("Vanilla Radar Sprites", "Artifice", true, "Adds new radar sprites for Artifice, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            AdamanceSprites = base.Config.Bind("Vanilla Radar Sprites", "Adamance", true, "Adds new radar sprites for Adamance, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            EmbrionSprites = base.Config.Bind("Vanilla Radar Sprites", "Embrion", true, "Adds new radar sprites for Embrion, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");
            GordionSprites = base.Config.Bind("Vanilla Radar Sprites", "Gordion", true, "Adds new radar sprites for Gordion, showing buildings, obstacles, catwalks, and more (will replace any vanilla radar objects).");

            ClearOrphans = base.Config.Bind("!Config Management", "Clear Orphaned Entries On Next Join", false, "This check box acts like a button which will only activate once then go back to being unchecked: after starting a game, all unused config data will be cleared. This means config entries associated with moons that are no longer installed or entries for modes which are no longer active for a given moon (e.g. if you switch a moon's mode from Manual to Automatic, the manual options will still be leftover in the file).");

            string configVersionString = "-1.-1.-1";
            ConfigDefinition configVersionDef = new ConfigDefinition("!Config Management", "Config Version");

            var orphanedEntriesProperty = base.Config.GetType().GetProperty("OrphanedEntries", BindingFlags.NonPublic | BindingFlags.Instance);
            Dictionary<ConfigDefinition, string> orphanedEntries = (Dictionary<ConfigDefinition, string>)orphanedEntriesProperty!.GetValue(base.Config, null);

            if (orphanedEntries.TryGetValue(configVersionDef, out string version))
            {
                UniversalRadar.Logger.LogDebug($"Found config version: {version} > {MyPluginInfo.PLUGIN_VERSION}");
                configVersionString = version;
            }

            ConfigVersion = base.Config.Bind("!Config Management", "Config Version", "-1.-1.-1", "Used for internal config tracking, please ignore.");

            string[] versionStringNums = configVersionString.Split(".");
            if (versionStringNums.Length != 3 || versionStringNums.Any(x => !int.TryParse(x, out int n)))
            {
                UniversalRadar.Logger.LogWarning("Invalid config version detected!");
                versionStringNums = ["-1", "-1", "-1"];
                ConfigVersion.Value = "-1.-1.-1";
            }
            configVersionArray = Array.ConvertAll(versionStringNums, x => int.Parse(x));

            batbyPresent = Chainloader.PluginInfos.ContainsKey("imabatby.lethallevelloader");
            zaggyPresent = Chainloader.PluginInfos.ContainsKey("Zaggy1024.TwoRadarMaps");

            dopaPresent = Chainloader.PluginInfos.ContainsKey("dopadream.lethalcompany.rebalancedmoons");
            spookyPresent = Chainloader.PluginInfos.ContainsKey("MapImprovements");
            terraformerPresent = Chainloader.PluginInfos.ContainsKey("TonightWeDine");

            string sAssemblyLocation = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            URAssets = AssetBundle.LoadFromFile(Path.Combine(sAssemblyLocation, "sburassets"));

            contourMaterial = (Material)URAssets.LoadAsset("ContourMat");
            radarFillMat0 = (Material)URAssets.LoadAsset("RadarGreen0");// regular
            radarFillMat1 = (Material)URAssets.LoadAsset("RadarGreen1");// low opacity
            radarWaterMat = (Material)URAssets.LoadAsset("RadarBlue");// water
            radarWaterMat.renderQueue = 1000;

            Patch();

            Logger.LogInfo($"{MyPluginInfo.PLUGIN_GUID} v{MyPluginInfo.PLUGIN_VERSION} has loaded!");
        }

        public static void SetTime()
        {
            storedTime = Time.realtimeSinceStartup;
        }

        public static float GetTime()
        {
            return Time.realtimeSinceStartup - storedTime;
        }

        internal static void Patch()
        {
            Harmony ??= new Harmony(MyPluginInfo.PLUGIN_GUID);

            Logger.LogDebug("Patching...");

            Harmony.PatchAll();

            Logger.LogDebug("Finished patching!");
        }

        internal static void Unpatch()
        {
            Logger.LogDebug("Unpatching...");

            Harmony?.UnpatchSelf();

            Logger.LogDebug("Finished unpatching!");
        }
    }


}
